//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int ID { get; set; }
        public int Room { get; set; }
        public int Count_Peoples { get; set; }
        public string Status { get; set; }
    }
}
